---
- name: Turn off swap
  raw: swapoff -a

- name: install APT Transport HTTPS
  package:
    name: apt-transport-https
    state: present

- name: add apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes

- name: Install k8s packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubernetes-cni=0.6.0-00

- name: Initialise kubeadm
  raw: kubeadm init
  register: kubeadmInitOut
  ignore_errors: yes

- name: Add user
  user:
    name: k8sops
    state: present
    shell: /bin/bash
    group: sudo
    home: /home/k8sops

- name: add kube config directory under $HOME
  file:
    path: /home/k8sops/.kube
    state: directory
    mode: 0755
    group: sudo
    owner: k8sops

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/k8sops/.kube/config
    remote_src: yes
    owner: k8sops
    group: sudo
